version: '3.9'

services:
  fastapi:
    container_name: fastapi
    build: .
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    networks:
      - backend
    environment:
      - MONGODB_URI=mongodb+srv://admin:85wMpqAjAYw5b8f2@cluster0.mb9g87r.mongodb.net/?retryWrites=true&w=majority
      - IS_LOCAL_MONGODB=False

networks:
  backend:
    driver: bridge
